# Generated by Django 3.2.7 on 2021-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(fields=('agenda_id', 'horario'), name='agenda_horario_unique'),
        ),
    ]
