# Generated by Django 3.2.7 on 2021-09-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RemoveConstraint(
            model_name='agenda',
            name='medico_horario_unique',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='horario',
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('medico', 'data_alocacao'), name='medico_horario_unique'),
        ),
        migrations.AddField(
            model_name='agendahorario',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.agenda'),
        ),
        migrations.AddField(
            model_name='agendahorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.horario'),
        ),
    ]
