# Generated by Django 3.2.7 on 2021-09-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210929_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.TimeField(unique=True, verbose_name='Hora'),
        ),
    ]
