# Generated by Django 3.2.7 on 2021-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_horario_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendahorario',
            name='horario',
            field=models.TimeField(unique=True, verbose_name='Horário'),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
